[package]
name = "stove"
authors = ["spuds"]
repository = "https://github.com/bananaturtlesandwich/stove"
description = "an editor for cooked unreal engine 4 map files"
readme = "README.md"
version = "0.7.0"
edition = "2021"

[dependencies]
unreal_asset = { git = "https://github.com/astrotechies/unrealmodding", package = "unreal_asset" }
unpak = "*"
glam = { version = "*", features = ["fast-math"] }
miniquad = "*"
egui = "*"
egui-miniquad = "*"
egui-notify = "*"
egui_file = "*"
byteorder = "*"
hashbrown = "*"
hex = "*"

[build-dependencies]
winres = "*"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
discord-rich-presence = "*"
autoupdater = { git = "https://github.com/localcc/autoupdater" }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
